export const techQuestions: Record<string, string[]> = {
  JavaScript: [
    "Can you explain the difference between let, const, and var in JavaScript?",
    "How does prototypal inheritance work in JavaScript?",
    "What are closures and how would you use them?",
    "Explain the event loop in JavaScript.",
    "How do you handle asynchronous operations in JavaScript?",
  ],
  TypeScript: [
    "What are the benefits of using TypeScript over JavaScript?",
    "Explain the difference between interfaces and types in TypeScript.",
    "How do you implement generics in TypeScript?",
    "What are decorators in TypeScript and how would you use them?",
    "How do you handle null and undefined in TypeScript?",
  ],
  React: [
    "Explain the virtual DOM and its benefits.",
    "What are hooks in React and how do they work?",
    "How do you manage state in React applications?",
    "Explain the component lifecycle in React.",
    "What are the performance optimization techniques in React?",
  ],
  "Next.js": [
    "What are the key features of Next.js?",
    "Explain the difference between SSR, SSG, and ISR in Next.js.",
    "How do you implement API routes in Next.js?",
    "What are the benefits of using the App Router in Next.js?",
    "How do you handle authentication in Next.js?",
  ],
  "Node.js": [
    "How does the event-driven architecture work in Node.js?",
    "What is the purpose of middleware in Express.js?",
    "How do you handle errors in Node.js applications?",
    "Explain the difference between process.nextTick() and setImmediate().",
    "How do you implement clustering in Node.js?",
  ],
  Python: [
    "What are decorators in Python and how would you use them?",
    "Explain the difference between lists and tuples in Python.",
    "How does memory management work in Python?",
    "What are generators and how do they work?",
    "How do you handle concurrency in Python?",
  ],
  Java: [
    "Explain the principles of OOP in Java.",
    "What are the differences between an interface and an abstract class?",
    "How does garbage collection work in Java?",
    "What are the new features introduced in Java 8 and later versions?",
    "How do you implement multithreading in Java?",
  ],
  "C#": [
    "What are the key features of C#?",
    "Explain the difference between value types and reference types.",
    "How does async/await work in C#?",
    "What are LINQ expressions and how would you use them?",
    "How do you implement dependency injection in C#?",
  ],
  SQL: [
    "What is normalization and why is it important?",
    "Explain the difference between INNER JOIN and LEFT JOIN.",
    "How do you optimize SQL queries for performance?",
    "What are indexes and how do they work?",
    "How do you handle transactions in SQL?",
  ],
  MongoDB: [
    "What are the key differences between MongoDB and relational databases?",
    "How do you design schemas in MongoDB?",
    "Explain the aggregation pipeline in MongoDB.",
    "How do you implement indexing in MongoDB?",
    "What are the strategies for handling large datasets in MongoDB?",
  ],
  AWS: [
    "What are the core services of AWS?",
    "How do you implement serverless architecture using AWS Lambda?",
    "Explain the difference between EC2, ECS, and EKS.",
    "How do you implement CI/CD pipelines in AWS?",
    "What are the best practices for security in AWS?",
  ],
  Docker: [
    "What are the benefits of containerization?",
    "Explain the difference between Docker and virtual machines.",
    "How do you optimize Docker images for size and security?",
    "What is Docker Compose and how would you use it?",
    "How do you implement networking between Docker containers?",
  ],
}

